### ISSUE TITLE
Possible USB TXN injection attack vector?

### ISSUE THREAD

**Issue by brianddk** [trezor/community#6] opened 2018-01-25 16:01 UTC
There was recently a paper ([Low-Level Attacks in BitcoinWallets](http://web.archive.org/web/20180125155338/http://www.research.ed.ac.uk/portal/files/43750879/paperEdit_2.pdf)) published that outlines HID transport attack vector on other HW wallets.  One attack (page 12, sec b.1-b.2) that seemed the most dangerous was the modification of destination and "change" addresses in TXNs as they are sent to a HW wallet for signing.  Obviously, the destination address that is signed is displayed on the Trezor before the user ACKs the TXN that would neuter such attacks, but is modification of the "change" address using this attack vector possible.

Or to state differently...

* Does Trezor FW ensure that "change" addresses are part of the same derivation path as the UTXOs that are signed.

Keep in mind this an attack at the transport layer so safeguards in the application layer may not suffice.

**Comment by jhoenicke** [comment] 2018-01-25 16:08
Change addresses are checked since version 1.5.x (don't remember the exact version).  The change address path must be in the same wallet as all input addresses and end with .../1/x, where x must be small enough.  Otherwise, it  is not regarded as change, must be confirmed by the user, and is added to the total sent amount.

**Comment by prusnak** [comment] 2018-01-25 16:16
Closing as per above comment. We already thought about this attack vector in advance, that's why there is a check.

**Closed by prusnak** 2018-01-25 16:16 UTC

**Comment by brianddk** [comment] 2018-01-25 17:03
Great news!  Looks like the paper came out 2 months ago, but has gotten tracktion this week since it is no longer behind a paywall. 

If it balloons into something you got a perfect "been there, done that".

Thx for keeping ahead of the curve!
